services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=your-secret-key
      - REDIS_URL=redis://redis:6379
      - PORT=3001
      - BCRYPT_ROUNDS=10
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=5242880
      - SESSION_SECRET=your-very-secret-key
    ports:
      - "3001:3001"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend